spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: debuggeandoideas-prod
    password: ASDFQEWRTYZXC
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
